name: Continous Integration Analysis
run-name: Doctrine Expression Test

on: [push]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Check out to master branch
        uses: actions/checkout@v4
        with:
            ref: master
            token: ${{ secrets.GITHUB_TOKEN || 'my_dummy_token' }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Verify PHP version
        run: php -v

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Test Code Logic
        run: composer test
