name: Continous Integration Analysis
run-name: Doctrine Expression Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to master branch
        uses: actions/checkout@v4
        with:
            ref: master
            token: ${{ secrets.GITHUB_TOKEN || 'my_dummy_token' }}
      - name: Install doctrine dependencies
        run: composer install
      - name: Test Code Logic
        run: composer test
